# Generated by Django 4.1.7 on 2023-06-13 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageobjet',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camping.event', verbose_name='Event'),
        ),
    ]
