# Generated by Django 4.1.7 on 2023-06-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0002_alter_imageobjet_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationconfirmation',
            name='kkia_transaction_code',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
